# Generated by Django 4.1.2 on 2023-07-21 03:51

import django.core.validators
from django.db import migrations, models
import marketing_data_analytics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), marketing_data_analytics.models.validate_positive_age])),
                ('gender', models.CharField(choices=[('', '選択してください'), ('M', '男性'), ('F', '女性')], max_length=2)),
                ('overall_satisfaction', models.IntegerField(choices=[('', '選択してください'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('food_satisfaction', models.IntegerField(choices=[('', '選択してください'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_satisfaction', models.IntegerField(choices=[('', '選択してください'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ambience_satisfaction', models.IntegerField(choices=[('', '選択してください'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('service_satisfaction', models.IntegerField(choices=[('', '選択してください'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('other_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
