# Generated by Django 4.1.2 on 2023-07-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_data_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='menu',
            field=models.CharField(choices=[('', '選択してください'), ('S', 'そば'), ('U', 'うどん'), ('R', 'ラーメン')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
